# Generated by Django 4.1.5 on 2023-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('team_lead', models.CharField(max_length=100)),
                ('team_member', models.CharField(max_length=100)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True)),
                ('scope', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
            ],
        ),
    ]
