# Generated by Django 4.1.5 on 2023-01-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_details_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='project_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
