# Generated by Django 4.1.5 on 2023-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_alter_client_project_details_alter_details_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
