# Generated by Django 4.1.5 on 2023-01-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_details_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
