# Generated by Django 4.1.5 on 2023-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_alter_details_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
