# Generated by Django 4.1.5 on 2023-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_alter_details_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
    ]
