# Generated by Django 4.1.5 on 2023-01-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_alter_details_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='project_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_app.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='serial_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('UPCOMING', 'Upcoming'), ('CLOSED', 'Closed')], max_length=15),
        ),
    ]
