# Generated by Django 4.1.5 on 2023-01-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_details_project_status_details_serial_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='serial_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='serial_num',
            field=models.PositiveIntegerField(),
        ),
    ]
