# Generated by Django 4.1.5 on 2023-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_alter_client_serial_num_alter_details_serial_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
